// 메인 페이지
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
// 컴포넌트
import Navbar from "../components/Navbar";
// 이미지
import aurora from "../assets/main/aurora.png";
import shadow from "../assets/main/shadow.svg";
import paper from "../assets/main/paper.png";

export default function Home() {
  return (
    <Div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src={aurora.src}
        alt="background"
        width={390}
        height={695}
        className="background"
      />

      <Image src={shadow.src} alt="shadow" fill className="shadow" />

      <Image
        src={paper.src}
        alt="paper"
        width={390}
        height={770}
        className="paper"
      />
    </Div>
  );
}

const Test = styled.div`
  position: relative;

  width: 100%;
  height: 695px;

  background-image: url(${aurora.src});
  background-repeat: no-repeat;
  background-size: cover;
`;

const Div = styled.div`
  position: relative;
  width: auto;
  height: auto;

  margin: 0;
  padding: 0;

  .background {
    width: 100%;
  }

  .shadow {
    transform: translateY(-100px);
    width: 100%;
  }

  .paper {
    width: 100%;
  }
`;
